### ISSUE TITLE
Dúvida a respeito das funcionalidades

### ISSUE THREAD

**Issue by mestr3** [claudiosmweb/woocommerce-itau-shopline#1]
Boa Tarde Cláudio,
Gostaria de saber se você pensa em desenvolver este plugin já com a possibilidade do retorno automático e da verificação de status das transações (por cron ou alternativa). Sei que seu trabalho é independente e que na maioria das vezes não existe apoio financeiro da comunidade, mas queria saber também se você tem uma estimativa de prazo de finalização e de valor das doações para viabilizar o projeto.

Obrigado.

**Comment by claudiosmweb** [comment]
Não tem retorno automático na API pra falar a verdade.
Precisa ser feito pela "sounda" que no caso vai ser por cron.
Não tenho prazo e muito menos valor para doações.
Então me surpreenda: http://claudiosmweb.com/doacoes
